#pragma once

typedef struct {
    const char *url;
    const char *service;
    const char *category_id;
    const char *category_name;
} AdTestEntry;

static const AdTestEntry AD_TESTS[] = {
  {"https://pagead2.googlesyndication.com/", "Google Ads / DoubleClick", "core-ad-networks", "Core ad networks"},
  {"https://googleads.g.doubleclick.net/", "Google Ads / DoubleClick", "core-ad-networks", "Core ad networks"},
  {"https://securepubads.g.doubleclick.net/", "Google Ads / DoubleClick", "core-ad-networks", "Core ad networks"},
  {"https://ad.doubleclick.net/", "Google Ads / DoubleClick", "core-ad-networks", "Core ad networks"},
  {"https://stats.g.doubleclick.net/", "Google Ads / DoubleClick", "core-ad-networks", "Core ad networks"},
  {"https://tpc.googlesyndication.com/", "Google Ads / DoubleClick", "core-ad-networks", "Core ad networks"},
  {"https://partner.googleadservices.com/", "Google Ads / DoubleClick", "core-ad-networks", "Core ad networks"},
  {"https://pagead2.googleadservices.com/", "Google Ads / DoubleClick", "core-ad-networks", "Core ad networks"},
  {"https://adservice.google.com/", "Google Ads / DoubleClick", "core-ad-networks", "Core ad networks"},
  {"https://adservice.google.de/", "Google Ads / DoubleClick", "core-ad-networks", "Core ad networks"},
  {"https://afs.googlesyndication.com/", "Google Ads / DoubleClick", "core-ad-networks", "Core ad networks"},
  {"https://aax.amazon-adsystem.com/", "Amazon Ads", "core-ad-networks", "Core ad networks"},
  {"https://c.amazon-adsystem.com/", "Amazon Ads", "core-ad-networks", "Core ad networks"},
  {"https://s.amazon-adsystem.com/", "Amazon Ads", "core-ad-networks", "Core ad networks"},
  {"https://mads.amazon-adsystem.com/", "Amazon Ads", "core-ad-networks", "Core ad networks"},
  {"https://fls-na.amazon-adsystem.com/", "Amazon Ads", "core-ad-networks", "Core ad networks"},
  {"https://adtago.s3.amazonaws.com/", "Amazon Ads", "core-ad-networks", "Core ad networks"},
  {"https://analyticsengine.s3.amazonaws.com/", "Amazon Ads", "core-ad-networks", "Core ad networks"},
  {"https://analytics.s3.amazonaws.com/", "Amazon Ads", "core-ad-networks", "Core ad networks"},
  {"https://advice-ads.s3.amazonaws.com/", "Amazon Ads", "core-ad-networks", "Core ad networks"},
  {"https://bat.bing.com/", "Microsoft Advertising", "core-ad-networks", "Core ad networks"},
  {"https://ads.microsoft.com/", "Microsoft Advertising", "core-ad-networks", "Core ad networks"},
  {"https://analytics.microsoft.com/", "Microsoft Advertising", "core-ad-networks", "Core ad networks"},
  {"https://c.bing.com/", "Microsoft Advertising", "core-ad-networks", "Core ad networks"},
  {"https://cdn.ads.microsoft.com/", "Microsoft Advertising", "core-ad-networks", "Core ad networks"},
  {"https://bingads.microsoft.com/", "Microsoft Advertising", "core-ad-networks", "Core ad networks"},
  {"https://ads.yahoo.com/", "Yahoo / Verizon / AOL", "core-ad-networks", "Core ad networks"},
  {"https://analytics.yahoo.com/", "Yahoo / Verizon / AOL", "core-ad-networks", "Core ad networks"},
  {"https://adtech.yahooinc.com/", "Yahoo / Verizon / AOL", "core-ad-networks", "Core ad networks"},
  {"https://udc.yahoo.com/", "Yahoo / Verizon / AOL", "core-ad-networks", "Core ad networks"},
  {"https://udcm.yahoo.com/", "Yahoo / Verizon / AOL", "core-ad-networks", "Core ad networks"},
  {"https://analytics.query.yahoo.com/", "Yahoo / Verizon / AOL", "core-ad-networks", "Core ad networks"},
  {"https://partnerads.ysm.yahoo.com/", "Yahoo / Verizon / AOL", "core-ad-networks", "Core ad networks"},
  {"https://gemini.yahoo.com/", "Yahoo / Verizon / AOL", "core-ad-networks", "Core ad networks"},
  {"https://log.fc.yahoo.com/", "Yahoo / Verizon / AOL", "core-ad-networks", "Core ad networks"},
  {"https://adserver-us.adtech.advertising.com/", "Yahoo / Verizon / AOL", "core-ad-networks", "Core ad networks"},
  {"https://static.criteo.net/", "Criteo", "core-ad-networks", "Core ad networks"},
  {"https://gum.criteo.com/", "Criteo", "core-ad-networks", "Core ad networks"},
  {"https://bidder.criteo.com/", "Criteo", "core-ad-networks", "Core ad networks"},
  {"https://sslwidget.criteo.com/", "Criteo", "core-ad-networks", "Core ad networks"},
  {"https://cas.criteo.com/", "Criteo", "core-ad-networks", "Core ad networks"},
  {"https://dis.criteo.com/", "Criteo", "core-ad-networks", "Core ad networks"},
  {"https://trc.taboola.com/", "Taboola", "core-ad-networks", "Core ad networks"},
  {"https://cdn.taboola.com/", "Taboola", "core-ad-networks", "Core ad networks"},
  {"https://images.taboola.com/", "Taboola", "core-ad-networks", "Core ad networks"},
  {"https://api.taboola.com/", "Taboola", "core-ad-networks", "Core ad networks"},
  {"https://vidstat.taboola.com/", "Taboola", "core-ad-networks", "Core ad networks"},
  {"https://widgets.outbrain.com/", "Outbrain", "core-ad-networks", "Core ad networks"},
  {"https://odb.outbrain.com/", "Outbrain", "core-ad-networks", "Core ad networks"},
  {"https://amplifypixel.outbrain.com/", "Outbrain", "core-ad-networks", "Core ad networks"},
  {"https://traffic.outbrain.com/", "Outbrain", "core-ad-networks", "Core ad networks"},
  {"https://log.outbrain.com/", "Outbrain", "core-ad-networks", "Core ad networks"},
  {"https://static.media.net/", "Media.net", "core-ad-networks", "Core ad networks"},
  {"https://contextual.media.net/", "Media.net", "core-ad-networks", "Core ad networks"},
  {"https://adservetx.media.net/", "Media.net", "core-ad-networks", "Core ad networks"},
  {"https://media.net/", "Media.net", "core-ad-networks", "Core ad networks"},
  {"https://ads.pubmatic.com/", "PubMatic", "programmatic-rtb", "Programmatic / RTB"},
  {"https://hbopenbid.pubmatic.com/", "PubMatic", "programmatic-rtb", "Programmatic / RTB"},
  {"https://image2.pubmatic.com/", "PubMatic", "programmatic-rtb", "Programmatic / RTB"},
  {"https://gads.pubmatic.com/", "PubMatic", "programmatic-rtb", "Programmatic / RTB"},
  {"https://ow.pubmatic.com/", "PubMatic", "programmatic-rtb", "Programmatic / RTB"},
  {"https://fastlane.rubiconproject.com/", "Magnite / Rubicon", "programmatic-rtb", "Programmatic / RTB"},
  {"https://pixel.rubiconproject.com/", "Magnite / Rubicon", "programmatic-rtb", "Programmatic / RTB"},
  {"https://ads.rubiconproject.com/", "Magnite / Rubicon", "programmatic-rtb", "Programmatic / RTB"},
  {"https://eus.rubiconproject.com/", "Magnite / Rubicon", "programmatic-rtb", "Programmatic / RTB"},
  {"https://s.update.rubiconproject.com/", "Magnite / Rubicon", "programmatic-rtb", "Programmatic / RTB"},
  {"https://prebid-server.rubiconproject.com/", "Magnite / Rubicon", "programmatic-rtb", "Programmatic / RTB"},
  {"https://us-u.openx.net/", "OpenX", "programmatic-rtb", "Programmatic / RTB"},
  {"https://u.openx.net/", "OpenX", "programmatic-rtb", "Programmatic / RTB"},
  {"https://rtb.openx.net/", "OpenX", "programmatic-rtb", "Programmatic / RTB"},
  {"https://delivery-us.openx.net/", "OpenX", "programmatic-rtb", "Programmatic / RTB"},
  {"https://jp-u.openx.net/", "OpenX", "programmatic-rtb", "Programmatic / RTB"},
  {"https://ib.adnxs.com/", "Xandr / AppNexus", "programmatic-rtb", "Programmatic / RTB"},
  {"https://secure.adnxs.com/", "Xandr / AppNexus", "programmatic-rtb", "Programmatic / RTB"},
  {"https://acdn.adnxs.com/", "Xandr / AppNexus", "programmatic-rtb", "Programmatic / RTB"},
  {"https://sin3-ib.adnxs.com/", "Xandr / AppNexus", "programmatic-rtb", "Programmatic / RTB"},
  {"https://nym1-ib.adnxs.com/", "Xandr / AppNexus", "programmatic-rtb", "Programmatic / RTB"},
  {"https://adnxs.com/", "Xandr / AppNexus", "programmatic-rtb", "Programmatic / RTB"},
  {"https://match.adsrvr.org/", "The Trade Desk", "programmatic-rtb", "Programmatic / RTB"},
  {"https://insight.adsrvr.org/", "The Trade Desk", "programmatic-rtb", "Programmatic / RTB"},
  {"https://js.adsrvr.org/", "The Trade Desk", "programmatic-rtb", "Programmatic / RTB"},
  {"https://bid.adsrvr.org/", "The Trade Desk", "programmatic-rtb", "Programmatic / RTB"},
  {"https://js-sec.indexww.com/", "Index Exchange / Casale", "programmatic-rtb", "Programmatic / RTB"},
  {"https://as-sec.casalemedia.com/", "Index Exchange / Casale", "programmatic-rtb", "Programmatic / RTB"},
  {"https://ssum-sec.casalemedia.com/", "Index Exchange / Casale", "programmatic-rtb", "Programmatic / RTB"},
  {"https://htlb.casalemedia.com/", "Index Exchange / Casale", "programmatic-rtb", "Programmatic / RTB"},
  {"https://r.casalemedia.com/", "Index Exchange / Casale", "programmatic-rtb", "Programmatic / RTB"},
  {"https://ap.lijit.com/", "Sovrn / Lijit", "programmatic-rtb", "Programmatic / RTB"},
  {"https://ce.lijit.com/", "Sovrn / Lijit", "programmatic-rtb", "Programmatic / RTB"},
  {"https://vap.lijit.com/", "Sovrn / Lijit", "programmatic-rtb", "Programmatic / RTB"},
  {"https://gslbeacon.lijit.com/", "Sovrn / Lijit", "programmatic-rtb", "Programmatic / RTB"},
  {"https://ads.sovrn.com/", "Sovrn / Lijit", "programmatic-rtb", "Programmatic / RTB"},
  {"https://track.adform.net/", "Adform", "programmatic-rtb", "Programmatic / RTB"},
  {"https://adx.adform.net/", "Adform", "programmatic-rtb", "Programmatic / RTB"},
  {"https://s1.adform.net/", "Adform", "programmatic-rtb", "Programmatic / RTB"},
  {"https://server.adform.net/", "Adform", "programmatic-rtb", "Programmatic / RTB"},
  {"https://x.bidswitch.net/", "Bidswitch / Sharethrough", "programmatic-rtb", "Programmatic / RTB"},
  {"https://simage2.pubmatic.com/", "Bidswitch / Sharethrough", "programmatic-rtb", "Programmatic / RTB"},
  {"https://native.sharethrough.com/", "Bidswitch / Sharethrough", "programmatic-rtb", "Programmatic / RTB"},
  {"https://match.sharethrough.com/", "Bidswitch / Sharethrough", "programmatic-rtb", "Programmatic / RTB"},
  {"https://www.google-analytics.com/", "Google Analytics / Tag Manager", "analytics-telemetry", "Analytics / telemetry"},
  {"https://ssl.google-analytics.com/", "Google Analytics / Tag Manager", "analytics-telemetry", "Analytics / telemetry"},
  {"https://google-analytics.com/", "Google Analytics / Tag Manager", "analytics-telemetry", "Analytics / telemetry"},
  {"https://analytics.google.com/", "Google Analytics / Tag Manager", "analytics-telemetry", "Analytics / telemetry"},
  {"https://region1.google-analytics.com/", "Google Analytics / Tag Manager", "analytics-telemetry", "Analytics / telemetry"},
  {"https://www.googletagmanager.com/", "Google Analytics / Tag Manager", "analytics-telemetry", "Analytics / telemetry"},
  {"https://googletagmanager.com/", "Google Analytics / Tag Manager", "analytics-telemetry", "Analytics / telemetry"},
  {"https://www.clarity.ms/", "Microsoft Clarity", "analytics-telemetry", "Analytics / telemetry"},
  {"https://c.clarity.ms/", "Microsoft Clarity", "analytics-telemetry", "Analytics / telemetry"},
  {"https://scripts.clarity.ms/", "Microsoft Clarity", "analytics-telemetry", "Analytics / telemetry"},
  {"https://a.clarity.ms/", "Microsoft Clarity", "analytics-telemetry", "Analytics / telemetry"},
  {"https://assets.adobedtm.com/", "Adobe Experience Cloud", "analytics-telemetry", "Analytics / telemetry"},
  {"https://dpm.demdex.net/", "Adobe Experience Cloud", "analytics-telemetry", "Analytics / telemetry"},
  {"https://fast.demdex.net/", "Adobe Experience Cloud", "analytics-telemetry", "Analytics / telemetry"},
  {"https://cm.everesttech.net/", "Adobe Experience Cloud", "analytics-telemetry", "Analytics / telemetry"},
  {"https://adobedc.demdex.net/", "Adobe Experience Cloud", "analytics-telemetry", "Analytics / telemetry"},
  {"https://sstats.adobe.com/", "Adobe Experience Cloud", "analytics-telemetry", "Analytics / telemetry"},
  {"https://script.hotjar.com/", "Hotjar", "analytics-telemetry", "Analytics / telemetry"},
  {"https://static.hotjar.com/", "Hotjar", "analytics-telemetry", "Analytics / telemetry"},
  {"https://identify.hotjar.com/", "Hotjar", "analytics-telemetry", "Analytics / telemetry"},
  {"https://events.hotjar.io/", "Hotjar", "analytics-telemetry", "Analytics / telemetry"},
  {"https://insights.hotjar.com/", "Hotjar", "analytics-telemetry", "Analytics / telemetry"},
  {"https://adm.hotjar.com/", "Hotjar", "analytics-telemetry", "Analytics / telemetry"},
  {"https://surveys.hotjar.com/", "Hotjar", "analytics-telemetry", "Analytics / telemetry"},
  {"https://cdn.segment.com/", "Segment", "analytics-telemetry", "Analytics / telemetry"},
  {"https://api.segment.io/", "Segment", "analytics-telemetry", "Analytics / telemetry"},
  {"https://events.segmentapis.com/", "Segment", "analytics-telemetry", "Analytics / telemetry"},
  {"https://cdn.mxpnl.com/", "Mixpanel", "analytics-telemetry", "Analytics / telemetry"},
  {"https://api-js.mixpanel.com/", "Mixpanel", "analytics-telemetry", "Analytics / telemetry"},
  {"https://api.mixpanel.com/", "Mixpanel", "analytics-telemetry", "Analytics / telemetry"},
  {"https://decide.mixpanel.com/", "Mixpanel", "analytics-telemetry", "Analytics / telemetry"},
  {"https://cdn.amplitude.com/", "Amplitude", "analytics-telemetry", "Analytics / telemetry"},
  {"https://api2.amplitude.com/", "Amplitude", "analytics-telemetry", "Analytics / telemetry"},
  {"https://regionconfig.amplitude.com/", "Amplitude", "analytics-telemetry", "Analytics / telemetry"},
  {"https://api.eu.amplitude.com/", "Amplitude", "analytics-telemetry", "Analytics / telemetry"},
  {"https://fullstory.com/", "FullStory", "analytics-telemetry", "Analytics / telemetry"},
  {"https://edge.fullstory.com/", "FullStory", "analytics-telemetry", "Analytics / telemetry"},
  {"https://rs.fullstory.com/", "FullStory", "analytics-telemetry", "Analytics / telemetry"},
  {"https://o-collector.fullstory.com/", "FullStory", "analytics-telemetry", "Analytics / telemetry"},
  {"https://mouseflow.com/", "Mouseflow", "analytics-telemetry", "Analytics / telemetry"},
  {"https://cdn.mouseflow.com/", "Mouseflow", "analytics-telemetry", "Analytics / telemetry"},
  {"https://o2.mouseflow.com/", "Mouseflow", "analytics-telemetry", "Analytics / telemetry"},
  {"https://gtm.mouseflow.com/", "Mouseflow", "analytics-telemetry", "Analytics / telemetry"},
  {"https://api.mouseflow.com/", "Mouseflow", "analytics-telemetry", "Analytics / telemetry"},
  {"https://tools.mouseflow.com/", "Mouseflow", "analytics-telemetry", "Analytics / telemetry"},
  {"https://luckyorange.com/", "Lucky Orange", "analytics-telemetry", "Analytics / telemetry"},
  {"https://api.luckyorange.com/", "Lucky Orange", "analytics-telemetry", "Analytics / telemetry"},
  {"https://realtime.luckyorange.com/", "Lucky Orange", "analytics-telemetry", "Analytics / telemetry"},
  {"https://cdn.luckyorange.com/", "Lucky Orange", "analytics-telemetry", "Analytics / telemetry"},
  {"https://w1.luckyorange.com/", "Lucky Orange", "analytics-telemetry", "Analytics / telemetry"},
  {"https://upload.luckyorange.net/", "Lucky Orange", "analytics-telemetry", "Analytics / telemetry"},
  {"https://cs.luckyorange.net/", "Lucky Orange", "analytics-telemetry", "Analytics / telemetry"},
  {"https://settings.luckyorange.net/", "Lucky Orange", "analytics-telemetry", "Analytics / telemetry"},
  {"https://script.crazyegg.com/", "Crazy Egg / Heap", "analytics-telemetry", "Analytics / telemetry"},
  {"https://tracking.crazyegg.com/", "Crazy Egg / Heap", "analytics-telemetry", "Analytics / telemetry"},
  {"https://cdn.heapanalytics.com/", "Crazy Egg / Heap", "analytics-telemetry", "Analytics / telemetry"},
  {"https://heapanalytics.com/", "Crazy Egg / Heap", "analytics-telemetry", "Analytics / telemetry"},
  {"https://c.heapanalytics.com/", "Crazy Egg / Heap", "analytics-telemetry", "Analytics / telemetry"},
  {"https://plausible.io/", "Plausible / Matomo", "analytics-telemetry", "Analytics / telemetry"},
  {"https://cdn.matomo.cloud/", "Plausible / Matomo", "analytics-telemetry", "Analytics / telemetry"},
  {"https://matomo.cloud/", "Plausible / Matomo", "analytics-telemetry", "Analytics / telemetry"},
  {"https://stats.wp.com/", "Plausible / Matomo", "analytics-telemetry", "Analytics / telemetry"},
  {"https://connect.facebook.net/", "Meta / Facebook", "social-pixels", "Social pixels"},
  {"https://pixel.facebook.com/", "Meta / Facebook", "social-pixels", "Social pixels"},
  {"https://an.facebook.com/", "Meta / Facebook", "social-pixels", "Social pixels"},
  {"https://www.facebook.com/", "Meta / Facebook", "social-pixels", "Social pixels"},
  {"https://graph.facebook.com/", "Meta / Facebook", "social-pixels", "Social pixels"},
  {"https://analytics.tiktok.com/", "TikTok", "social-pixels", "Social pixels"},
  {"https://ads.tiktok.com/", "TikTok", "social-pixels", "Social pixels"},
  {"https://ads-api.tiktok.com/", "TikTok", "social-pixels", "Social pixels"},
  {"https://analytics-sg.tiktok.com/", "TikTok", "social-pixels", "Social pixels"},
  {"https://ads-sg.tiktok.com/", "TikTok", "social-pixels", "Social pixels"},
  {"https://business-api.tiktok.com/", "TikTok", "social-pixels", "Social pixels"},
  {"https://log.byteoversea.com/", "TikTok", "social-pixels", "Social pixels"},
  {"https://mon.tiktokv.com/", "TikTok", "social-pixels", "Social pixels"},
  {"https://static.ads-twitter.com/", "X / Twitter", "social-pixels", "Social pixels"},
  {"https://analytics.twitter.com/", "X / Twitter", "social-pixels", "Social pixels"},
  {"https://ads-api.twitter.com/", "X / Twitter", "social-pixels", "Social pixels"},
  {"https://ads-twitter.com/", "X / Twitter", "social-pixels", "Social pixels"},
  {"https://snap.licdn.com/", "LinkedIn", "social-pixels", "Social pixels"},
  {"https://ads.linkedin.com/", "LinkedIn", "social-pixels", "Social pixels"},
  {"https://px.ads.linkedin.com/", "LinkedIn", "social-pixels", "Social pixels"},
  {"https://analytics.pointdrive.linkedin.com/", "LinkedIn", "social-pixels", "Social pixels"},
  {"https://ads.pinterest.com/", "Pinterest", "social-pixels", "Social pixels"},
  {"https://log.pinterest.com/", "Pinterest", "social-pixels", "Social pixels"},
  {"https://analytics.pinterest.com/", "Pinterest", "social-pixels", "Social pixels"},
  {"https://trk.pinterest.com/", "Pinterest", "social-pixels", "Social pixels"},
  {"https://events.reddit.com/", "Reddit", "social-pixels", "Social pixels"},
  {"https://events.redditmedia.com/", "Reddit", "social-pixels", "Social pixels"},
  {"https://alb.reddit.com/", "Reddit", "social-pixels", "Social pixels"},
  {"https://tr.snapchat.com/", "Snapchat", "social-pixels", "Social pixels"},
  {"https://ads.snapchat.com/", "Snapchat", "social-pixels", "Social pixels"},
  {"https://sc-static.net/", "Snapchat", "social-pixels", "Social pixels"},
  {"https://q.quora.com/", "Quora / Nextdoor", "social-pixels", "Social pixels"},
  {"https://ads-api.nextdoor.com/", "Quora / Nextdoor", "social-pixels", "Social pixels"},
  {"https://pixel.nextdoor.com/", "Quora / Nextdoor", "social-pixels", "Social pixels"},
  {"https://app.adjust.com/", "Adjust", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://app.adjust.net/", "Adjust", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://view.adjust.com/", "Adjust", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://app.adjust.world/", "Adjust", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://gdpr.adjust.com/", "Adjust", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://app.appsflyer.com/", "AppsFlyer", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://t.appsflyer.com/", "AppsFlyer", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://events.appsflyer.com/", "AppsFlyer", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://cdn-settings.appsflyersdk.com/", "AppsFlyer", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://conversions.appsflyer.com/", "AppsFlyer", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://api2.branch.io/", "Branch", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://cdn.branch.io/", "Branch", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://sdk.branch.io/", "Branch", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://v1.branch.io/", "Branch", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://control.kochava.com/", "Kochava", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://kvinit-prod.api.kochava.com/", "Kochava", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://tracker.kochava.com/", "Kochava", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://imp.control.kochava.com/", "Kochava", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://auction.unityads.unity3d.com/", "Unity Ads", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://webview.unityads.unity3d.com/", "Unity Ads", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://config.unityads.unity3d.com/", "Unity Ads", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://adserver.unityads.unity3d.com/", "Unity Ads", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://d.applovin.com/", "AppLovin", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://a.applovin.com/", "AppLovin", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://ms.applovin.com/", "AppLovin", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://rt.applovin.com/", "AppLovin", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://res1.applovin.com/", "AppLovin", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://ads.api.vungle.com/", "Vungle / Liftoff", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://api.vungle.com/", "Vungle / Liftoff", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://config.ads.vungle.com/", "Vungle / Liftoff", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://events.ads.vungle.com/", "Vungle / Liftoff", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://init.supersonicads.com/", "ironSource / Fyber / Inneractive", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://outcome-ssp.supersonicads.com/", "ironSource / Fyber / Inneractive", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://sdk-events.inner-active.mobi/", "ironSource / Fyber / Inneractive", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://cdn2.inner-active.mobi/", "ironSource / Fyber / Inneractive", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://ads.nexage.com/", "ironSource / Fyber / Inneractive", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://live.chartboost.com/", "Chartboost", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://da.chartboost.com/", "Chartboost", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://api.chartboost.com/", "Chartboost", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://ads30.adcolony.com/", "AdColony", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://adc3-launch.adcolony.com/", "AdColony", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://events3alt.adcolony.com/", "AdColony", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://wd.adcolony.com/", "AdColony", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://sdk-api.mintegral.com/", "Mintegral / Rayjump", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://net.rayjump.com/", "Mintegral / Rayjump", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://setting.rayjump.com/", "Mintegral / Rayjump", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://detect.rayjump.com/", "Mintegral / Rayjump", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://sdkm.w.inmobi.com/", "InMobi", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://telemetry.sdk.inmobi.com/", "InMobi", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://i.l.inmobicdn.net/", "InMobi", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://config.inmobi.com/", "InMobi", "mobile-app-ads", "Mobile app ads / attribution"},
  {"https://browser.sentry-cdn.com/", "Sentry", "error-session-replay", "Error, RUM and session replay"},
  {"https://app.getsentry.com/", "Sentry", "error-session-replay", "Error, RUM and session replay"},
  {"https://o0.ingest.sentry.io/", "Sentry", "error-session-replay", "Error, RUM and session replay"},
  {"https://sentry.io/", "Sentry", "error-session-replay", "Error, RUM and session replay"},
  {"https://notify.bugsnag.com/", "Bugsnag", "error-session-replay", "Error, RUM and session replay"},
  {"https://sessions.bugsnag.com/", "Bugsnag", "error-session-replay", "Error, RUM and session replay"},
  {"https://api.bugsnag.com/", "Bugsnag", "error-session-replay", "Error, RUM and session replay"},
  {"https://app.bugsnag.com/", "Bugsnag", "error-session-replay", "Error, RUM and session replay"},
  {"https://browser-intake-datadoghq.com/", "Datadog RUM", "error-session-replay", "Error, RUM and session replay"},
  {"https://browser-intake-datadoghq.eu/", "Datadog RUM", "error-session-replay", "Error, RUM and session replay"},
  {"https://rum.browser-intake-datadoghq.com/", "Datadog RUM", "error-session-replay", "Error, RUM and session replay"},
  {"https://bam.nr-data.net/", "New Relic", "error-session-replay", "Error, RUM and session replay"},
  {"https://js-agent.newrelic.com/", "New Relic", "error-session-replay", "Error, RUM and session replay"},
  {"https://bam-cell.nr-data.net/", "New Relic", "error-session-replay", "Error, RUM and session replay"},
  {"https://api.rollbar.com/", "Rollbar / Raygun", "error-session-replay", "Error, RUM and session replay"},
  {"https://browser-intake-us5-datadoghq.com/", "Rollbar / Raygun", "error-session-replay", "Error, RUM and session replay"},
  {"https://api.raygun.io/", "Rollbar / Raygun", "error-session-replay", "Error, RUM and session replay"},
  {"https://cdn.lr-ingest.com/", "LogRocket", "error-session-replay", "Error, RUM and session replay"},
  {"https://r.lr-ingest.com/", "LogRocket", "error-session-replay", "Error, RUM and session replay"},
  {"https://i.logrocket.com/", "LogRocket", "error-session-replay", "Error, RUM and session replay"},
  {"https://cdn.logrocket.io/", "LogRocket", "error-session-replay", "Error, RUM and session replay"},
  {"https://www.awin1.com/", "Awin / Zanox", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://awin1.com/", "Awin / Zanox", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://www.zanox-affiliate.de/", "Awin / Zanox", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://ad.zanox.com/", "Awin / Zanox", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://click.linksynergy.com/", "Rakuten / LinkShare", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://ad.linksynergy.com/", "Rakuten / LinkShare", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://analytics.linksynergy.com/", "Rakuten / LinkShare", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://t.tradedoubler.com/", "Tradedoubler", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://clk.tradedoubler.com/", "Tradedoubler", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://imp.tradedoubler.com/", "Tradedoubler", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://tradedoubler.com/", "Tradedoubler", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://track.webgains.com/", "Webgains / Partnerize", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://track.webgains.org/", "Webgains / Partnerize", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://prf.hn/", "Webgains / Partnerize", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://t.myvisualiq.net/", "Webgains / Partnerize", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://www.emjcd.com/", "CJ / ShareASale / Impact", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://www.anrdoezrs.net/", "CJ / ShareASale / Impact", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://shareasale.com/", "CJ / ShareASale / Impact", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://impact.com/", "CJ / ShareASale / Impact", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://trk.impact.com/", "CJ / ShareASale / Impact", "affiliate-conversion", "Affiliate / conversion tracking"},
  {"https://api.ad.xiaomi.com/", "Xiaomi", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://data.mistat.xiaomi.com/", "Xiaomi", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://data.mistat.india.xiaomi.com/", "Xiaomi", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://data.mistat.rus.xiaomi.com/", "Xiaomi", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://sdkconfig.ad.xiaomi.com/", "Xiaomi", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://sdkconfig.ad.intl.xiaomi.com/", "Xiaomi", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://tracking.rus.miui.com/", "Xiaomi", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://samsungads.com/", "Samsung", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://smetrics.samsung.com/", "Samsung", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://nmetrics.samsung.com/", "Samsung", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://samsung-com.112.2o7.net/", "Samsung", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://analytics-api.samsunghealthcn.com/", "Samsung", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://log-config.samsungacr.com/", "Samsung", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://metrics.data.hicloud.com/", "Huawei", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://metrics2.data.hicloud.com/", "Huawei", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://grs.hicloud.com/", "Huawei", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://logservice.hicloud.com/", "Huawei", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://logservice1.hicloud.com/", "Huawei", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://logbak.hicloud.com/", "Huawei", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://adsfs.oppomobile.com/", "Oppo / Realme / OnePlus", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://adx.ads.oppomobile.com/", "Oppo / Realme / OnePlus", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://ck.ads.oppomobile.com/", "Oppo / Realme / OnePlus", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://data.ads.oppomobile.com/", "Oppo / Realme / OnePlus", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://iot-eu-logser.realme.com/", "Oppo / Realme / OnePlus", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://bdapi-ads.realmemobile.com/", "Oppo / Realme / OnePlus", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://click.oneplus.cn/", "Oppo / Realme / OnePlus", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://open.oneplus.net/", "Oppo / Realme / OnePlus", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://iadsdk.apple.com/", "Apple Ads / metrics", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://api-adservices.apple.com/", "Apple Ads / metrics", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://metrics.icloud.com/", "Apple Ads / metrics", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://metrics.mzstatic.com/", "Apple Ads / metrics", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://books-analytics-events.apple.com/", "Apple Ads / metrics", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://weather-analytics-events.apple.com/", "Apple Ads / metrics", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://notes-analytics-events.apple.com/", "Apple Ads / metrics", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://ads.roku.com/", "Roku / LG / Vizio", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://p.ads.roku.com/", "Roku / LG / Vizio", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://scribe.logs.roku.com/", "Roku / LG / Vizio", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://us.info.lgsmartad.com/", "Roku / LG / Vizio", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://ad.lgappstv.com/", "Roku / LG / Vizio", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://tvinteractive.tv/", "Roku / LG / Vizio", "oem-tv-telemetry", "OEM / TV / device telemetry"},
  {"https://extmaps-api.yandex.net/", "Yandex", "regional-adtech", "Regional adtech"},
  {"https://appmetrica.yandex.ru/", "Yandex", "regional-adtech", "Regional adtech"},
  {"https://adfstat.yandex.ru/", "Yandex", "regional-adtech", "Regional adtech"},
  {"https://metrika.yandex.ru/", "Yandex", "regional-adtech", "Regional adtech"},
  {"https://offerwall.yandex.net/", "Yandex", "regional-adtech", "Regional adtech"},
  {"https://adfox.yandex.ru/", "Yandex", "regional-adtech", "Regional adtech"},
  {"https://mc.yandex.ru/", "Yandex", "regional-adtech", "Regional adtech"},
  {"https://hm.baidu.com/", "Baidu", "regional-adtech", "Regional adtech"},
  {"https://eclick.baidu.com/", "Baidu", "regional-adtech", "Regional adtech"},
  {"https://cpro.baidu.com/", "Baidu", "regional-adtech", "Regional adtech"},
  {"https://pos.baidu.com/", "Baidu", "regional-adtech", "Regional adtech"},
  {"https://dup.baidustatic.com/", "Baidu", "regional-adtech", "Regional adtech"},
  {"https://tajs.qq.com/", "Tencent / Alibaba", "regional-adtech", "Regional adtech"},
  {"https://pingjs.qq.com/", "Tencent / Alibaba", "regional-adtech", "Regional adtech"},
  {"https://e.qq.com/", "Tencent / Alibaba", "regional-adtech", "Regional adtech"},
  {"https://acjs.aliyun.com/", "Tencent / Alibaba", "regional-adtech", "Regional adtech"},
  {"https://atanx.alicdn.com/", "Tencent / Alibaba", "regional-adtech", "Regional adtech"},
  {"https://adcr.naver.com/", "Kakao / Naver", "regional-adtech", "Regional adtech"},
  {"https://wcs.naver.net/", "Kakao / Naver", "regional-adtech", "Regional adtech"},
  {"https://adimg3.search.naver.net/", "Kakao / Naver", "regional-adtech", "Regional adtech"},
  {"https://display.ad.daum.net/", "Kakao / Naver", "regional-adtech", "Regional adtech"},
  {"https://track.tiara.daum.net/", "Kakao / Naver", "regional-adtech", "Regional adtech"},
  {"https://adtimaserver.vn/", "Vietnam ad networks", "regional-adtech", "Regional adtech"},
  {"https://api.adtimaserver.vn/", "Vietnam ad networks", "regional-adtech", "Regional adtech"},
  {"https://log.adtimaserver.vn/", "Vietnam ad networks", "regional-adtech", "Regional adtech"},
  {"https://media.adtimaserver.vn/", "Vietnam ad networks", "regional-adtech", "Regional adtech"},
  {"https://static.adtimaserver.vn/", "Vietnam ad networks", "regional-adtech", "Regional adtech"},
  {"https://static2.adtimaserver.vn/", "Vietnam ad networks", "regional-adtech", "Regional adtech"},
  {"https://stream.adtimaserver.vn/", "Vietnam ad networks", "regional-adtech", "Regional adtech"},
  {"https://top-fwz1.mail.ru/", "VK / Mail.ru", "regional-adtech", "Regional adtech"},
  {"https://ad.mail.ru/", "VK / Mail.ru", "regional-adtech", "Regional adtech"},
  {"https://rs.mail.ru/", "VK / Mail.ru", "regional-adtech", "Regional adtech"},
  {"https://ads.vk.com/", "VK / Mail.ru", "regional-adtech", "Regional adtech"},
  {"https://vk-ads.com/", "VK / Mail.ru", "regional-adtech", "Regional adtech"},
  {"https://cdn.cookielaw.org/", "OneTrust", "consent-annoyance", "Consent / privacy overlays"},
  {"https://geolocation.onetrust.com/", "OneTrust", "consent-annoyance", "Consent / privacy overlays"},
  {"https://privacyportal.onetrust.com/", "OneTrust", "consent-annoyance", "Consent / privacy overlays"},
  {"https://cookie-cdn.cookiepro.com/", "OneTrust", "consent-annoyance", "Consent / privacy overlays"},
  {"https://consent.cookiebot.com/", "Cookiebot", "consent-annoyance", "Consent / privacy overlays"},
  {"https://consentcdn.cookiebot.com/", "Cookiebot", "consent-annoyance", "Consent / privacy overlays"},
  {"https://imgsct.cookiebot.com/", "Cookiebot", "consent-annoyance", "Consent / privacy overlays"},
  {"https://cmp.quantcast.com/", "Quantcast Choice", "consent-annoyance", "Consent / privacy overlays"},
  {"https://choice.quantcast.com/", "Quantcast Choice", "consent-annoyance", "Consent / privacy overlays"},
  {"https://quantcast.mgr.consensu.org/", "Quantcast Choice", "consent-annoyance", "Consent / privacy overlays"},
  {"https://sourcepoint.mgr.consensu.org/", "Sourcepoint / Didomi", "consent-annoyance", "Consent / privacy overlays"},
  {"https://cdn.privacy-mgmt.com/", "Sourcepoint / Didomi", "consent-annoyance", "Consent / privacy overlays"},
  {"https://api.privacy-center.org/", "Sourcepoint / Didomi", "consent-annoyance", "Consent / privacy overlays"},
  {"https://sdk.privacy-center.org/", "Sourcepoint / Didomi", "consent-annoyance", "Consent / privacy overlays"},
  {NULL, NULL, NULL, NULL}
};
